ALTER TABLE file_tasks
    ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS error_code VARCHAR(64),
    ADD COLUMN IF NOT EXISTS created_request_id VARCHAR(64),
    ADD COLUMN IF NOT EXISTS total_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS success_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS failed_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS running_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item_results_json TEXT;
